name: Publication d'un projet 📝
description: Proposez ici votre article d'un projet pour le HackLab !
labels: ["projet", "review-needed"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Merci de remplir le _titre de l'issue_ sous la forme suivante :**  
        `Nouveau projet: [Votre pseudo] - [Nom du projet]`
  - type: input
    id: title
    attributes:
      label: Titre du projet
      placeholder: "Ex: LNKat"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Courte description du projet (1 ou 2 phrases)
      placeholder: "Ce projet consiste à..."
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Contenu complet (en Markdown)
      placeholder: |
        ## Introduction
        ...
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Auteur
      placeholder: "Ex: HackLab ESGI"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Lien github du projet
      placeholder: "https://github.com/hacklab-esgi/LNKat"
    validations:
      required: true
