name: 🛠️ Créer un article depuis une Issue

on:
  issues:
    types: [opened, edited]

jobs:
  create-article:
    if: contains(github.event.issue.labels.*.name, 'article')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Nettoyer les données de l'Issue
        id: extract
        run: |
          BODY=$(echo "${{ github.event.issue.body }}")

          TITLE=$(echo "$BODY" | awk '/^### Titre de l.Article/{getline; print}' | xargs)
          DESCRIPTION=$(echo "$BODY" | awk '/^### Description/{getline; print}' | xargs)
          AUTHOR=$(echo "$BODY" | awk '/^### Auteur/{getline; print}' | xargs)
          TAGS=$(echo "$BODY" | awk '/^### Tags/{getline; print}' | xargs)

          # Extrait tout le contenu après "### Contenu complet" jusqu'à la fin
          CONTENT=$(echo "$BODY" | awk '/^### Contenu complet/{found=1; next} found' | sed 's/^/  /')

          SLUG=$(echo "$TITLE" | iconv -f utf8 -t ascii//TRANSLIT | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|-+$//g')
          DATE=$(date +"%d-%m-%Y")

          echo "slug=$SLUG" >> $GITHUB_OUTPUT
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

          # On sauve temporairement CONTENT dans un fichier séparé
          echo "$CONTENT" > content_temp.txt

      - name: Créer l'article
        run: |
          mkdir -p content/posts

          FILE="content/posts/${{ steps.extract.outputs.slug }}.md"

          if [ -f "$FILE" ]; then
            echo "❌ Le fichier existe déjà, on stoppe."
            exit 1
          fi

          echo "---" > "$FILE"
          echo "title: \"${{ steps.extract.outputs.title }}\"" >> "$FILE"
          echo "description: \"${{ steps.extract.outputs.description }}\"" >> "$FILE"
          echo "createdAt: \"${{ steps.extract.outputs.date }}\"" >> "$FILE"
          echo "author: \"${{ steps.extract.outputs.author }}\"" >> "$FILE"
          echo "draft: true" >> "$FILE"
          echo "tags:" >> "$FILE"

          for tag in $(echo "${{ steps.extract.outputs.tags }}" | tr ',' '\n'); do
            echo "  - $(echo $tag | xargs)" >> "$FILE"
          done

          echo "---" >> "$FILE"
          echo "" >> "$FILE"

          # Ajoute proprement le contenu
          cat content_temp.txt >> "$FILE"

          # Nettoyage du fichier temporaire
          rm content_temp.txt


      - name: Commit + Push dans main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📝 Nouvel article: ${{ steps.extract.outputs.title }}"
          branch: master
