name: 🛠️ Créer un article depuis une Issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-post:
    if: contains(github.event.issue.labels.*.name, 'article')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👉🏼 master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Fix remote HEAD 🛠
        run: |
          git remote set-head origin -a

      - name: Extraction des données de l'Issue
        id: extract
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.txt

          TITLE=$(awk '/^### Titre de l'\''Article/ {while (getline && $0 == ""); print}' issue_body.txt | xargs)
          DESCRIPTION=$(awk '/^### Description/ {while (getline && $0 == ""); print}' issue_body.txt | xargs)
          CONTENT=$(awk '/^### Contenu complet/ {flag=1; next} /^### Auteur/ {flag=0} flag' issue_body.txt | sed 's/\r//' )
          AUTHOR=$(awk '/^### Auteur/ {while (getline && $0 == ""); print}' issue_body.txt | xargs)
          TAGS=$(awk '/^### Tags/ {while (getline && $0 == ""); print}' issue_body.txt | xargs)

          echo "DEBUG: TITLE='$TITLE'"
          echo "DEBUG: DESCRIPTION='$DESCRIPTION'"
          echo "DEBUG: AUTHOR='$AUTHOR'"
          echo "DEBUG: TAGS='$TAGS'"

          # Vérification des champs
          if [ -z "$TITLE" ]; then
            echo "❌ ERREUR: Le champ 'Titre' est vide dans l'issue." >&2
            exit 1
          fi

          if [ -z "$DESCRIPTION" ]; then
            echo "❌ ERREUR: Le champ 'Description' est vide dans l'issue." >&2
            exit 1
          fi

          if [ -z "$CONTENT" ]; then
            echo "❌ ERREUR: Le champ 'Contenu complet' est vide dans l'issue." >&2
            exit 1
          fi

          if [ -z "$AUTHOR" ]; then
            echo "❌ ERREUR: Le champ 'Auteur' est vide dans l'issue." >&2
            exit 1
          fi

          if [ -z "$TAGS" ]; then
            echo "❌ ERREUR: Le champ 'Tags' est vide dans l'issue." >&2
            exit 1
          fi

          echo "TITLE<<EOF" >> $GITHUB_ENV
          echo "$TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$DESCRIPTION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "TAGS=$TAGS" >> $GITHUB_ENV


      - name: Générer le slug et créer la branche
        run: |
          echo "TITLE récupéré: '${{ env.TITLE }}'" # ➔ vérification visuelle
          slug=$(echo "${{ env.TITLE }}" | iconv -f utf8 -t ascii//TRANSLIT \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/[^a-z0-9]/-/g' \
            | sed 's/-\+/-/g' \
            | sed 's/^-//;s/-$//')

          echo "Slug généré: $slug"

          echo "SLUG=$slug" >> $GITHUB_ENV

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b article-$slug

      - name: Nettoyer le fichier temporaire issue_body.txt
        run: rm -f issue_body.txt

      - name: S'assurer que src/content/posts existe
        run: |
          mkdir -p src/content/posts
          touch src/content/posts/.gitkeep
          git add src/content/posts/.gitkeep
          git commit -m "chore: prepare posts directory" || echo "Pas de changements"
          git push origin master || echo "Pas besoin de push"


      - name: Générer le fichier article
        run: |
          DATE=$(date +"%d-%m-%Y")
          FILE="src/content/posts/${{ env.SLUG }}.mdx"

          echo "---" > "$FILE"
          echo "title: \"${{ env.TITLE }}\"" >> "$FILE"
          echo "description: \"${{ env.DESCRIPTION }}\"" >> "$FILE"
          echo "createdAt: $DATE" >> "$FILE"
          echo "author: \"${{ env.AUTHOR }}\"" >> "$FILE"
          echo "draft: true" >> "$FILE"
          echo "tags:" >> "$FILE"
          for tag in $(echo "${{ env.TAGS }}" | tr ',' '\n'); do
            echo "  - $(echo $tag | xargs)" >> "$FILE"
          done
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "${{ env.CONTENT }}" >> "$FILE"

      - name: Commit les changements
        run: |
          ls -al src/content/posts/
          git checkout
          git add --force src/content/posts/${{ env.SLUG }}.mdx
          git checkout
          git commit -m "📝 Proposer article: ${{ env.TITLE }}"
          git checkout

      - name: Vérification complète avant Push 🔎
        run: |
          echo "🧹 Status Git:"
          git status

          echo "🧾 Derniers commits:"
          git log --oneline -n 5

          echo "📂 Liste des fichiers trackés par Git:"
          git ls-files --stage

          echo "📁 Contenu du dossier src/content/posts/:"
          ls -al src/content/posts/



      - name: Push vers remote
        run: |
          git push --force --set-upstream origin article-${{ env.SLUG }}
          git checkout


      - name: Créer Pull Request 🔀
        uses: peter-evans/create-pull-request@v5
        with:
          title: "📝 Proposition: ${{ env.TITLE }}"
          body: |
            Article proposé automatiquement depuis une Issue.
            Merci de le relire avant publication.
          base: master
          branch: article-${{ env.SLUG }}
