name: 🛠️ Créer un article depuis une Issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-article:
    if: contains(github.event.issue.labels.*.name, 'article')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Extraction des données de l'Issue
        id: extract
        run: |
          echo "TITLE=$(echo \"${{ github.event.issue.body }}\" | grep -oP '(?<=\*\*Titre de l\'Article\*\*\n).*' | head -n 1 | sed 's/\r//g')" >> "$GITHUB_ENV"
          echo "DESCRIPTION=$(echo \"${{ github.event.issue.body }}\" | grep -oP '(?<=\*\*Description\*\*\n).*' | head -n 1 | sed 's/\r//g')" >> "$GITHUB_ENV"
          echo "CONTENT=$(echo \"${{ github.event.issue.body }}\" | awk '/\*\*Contenu complet/ {flag=1; next} /\*\*Auteur/ {flag=0} flag' | sed 's/\r//g')" >> "$GITHUB_ENV"
          echo "AUTHOR=$(echo \"${{ github.event.issue.body }}\" | grep -oP '(?<=\*\*Auteur\*\*\n).*' | head -n 1 | sed 's/\r//g')" >> "$GITHUB_ENV"
          echo "TAGS=$(echo \"${{ github.event.issue.body }}\" | grep -oP '(?<=\*\*Tags \(s\u00e9par\u00e9s par des virgules\)\*\*\n).*' | head -n 1 | sed 's/\r//g')" >> "$GITHUB_ENV"


      - name: Génération du fichier article
        run: |
          SLUG=$(echo "$TITLE" | iconv -f utf8 -t ascii//TRANSLIT | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-\+/-/g' | sed 's/^-//;s/-$//')
          DATE=$(date +"%d-%m-%Y")
          FILE="src/content/posts/$SLUG.md"

          mkdir -p src/content/posts

          echo "---" > "$FILE"
          echo "title: \"$TITLE\"" >> "$FILE"
          echo "description: \"$DESCRIPTION\"" >> "$FILE"
          echo "createdAt: $DATE" >> "$FILE"
          echo "author: $AUTHOR" >> "$FILE"
          echo "draft: true" >> "$FILE"
          echo "tags:" >> "$FILE"
          for tag in $(echo $TAGS | tr ',' '\n'); do
            echo "  - $(echo $tag | xargs)" >> "$FILE"
          done
          echo "---" >> "$FILE"

          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"

      - name: Commit + Push dans main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📝 Nouveau post: $TITLE"
          branch: article/${{ env.SLUG }}
          create_branch: true

      - name: Créer une Pull Request 🔀
        uses: peter-evans/create-pull-request@v5
        with:
          title: "📝 Proposition d'article: $TITLE"
          body: "Cet article a été proposé automatiquement depuis une Issue.\n\nMerci de le relire et de valider !"
          labels: article
          base: master
          branch: article/${{ env.SLUG }}