name: 🛠️ Créer un article depuis une Issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-post:
    if: contains(github.event.issue.labels.*.name, 'article')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👉🏼 Repo
        uses: actions/checkout@v4

      - name: Extraction des données de l'Issue
        id: extract
        run: |
          # Écrire le body brut dans un fichier texte
          echo "${{ github.event.issue.body }}" > issue_body.txt

          # Lire correctement depuis ce fichier sans exécuter
          TITLE=$(awk '/^### Titre de l'\''Article/{getline; print}' issue_body.txt | xargs)
          DESCRIPTION=$(awk '/^### Description/{getline; print}' issue_body.txt | xargs)
          AUTHOR=$(awk '/^### Auteur/{getline; print}' issue_body.txt | xargs)
          TAGS=$(awk '/^### Tags/{getline; print}' issue_body.txt | xargs)

          CONTENT=$(awk '/^### Contenu complet/{flag=1; next} /^### Auteur/{flag=0} flag' issue_body.txt)

          echo "TITLE<<EOF" >> $GITHUB_ENV
          echo "$TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$DESCRIPTION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "TAGS=$TAGS" >> $GITHUB_ENV

          echo "CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV



      - name: Générer le fichier article
        run: |
          SLUG=$(echo "$TITLE" | iconv -f utf8 -t ascii//TRANSLIT | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-\+/-/g' | sed 's/^-//;s/-$//')
          DATE=$(date +"%Y-%m-%d")
          FILE="src/content/posts/$SLUG.md"

          mkdir -p src/content/posts

          echo "---" > "$FILE"
          echo "title: \"$TITLE\"" >> "$FILE"
          echo "description: \"$DESCRIPTION\"" >> "$FILE"
          echo "createdAt: $DATE" >> "$FILE"
          echo "author: \"$AUTHOR\"" >> "$FILE"
          echo "draft: true" >> "$FILE"
          echo "tags:" >> "$FILE"
          for tag in $(echo $TAGS | tr ',' '\n'); do
            echo "  - $(echo $tag | xargs)" >> "$FILE"
          done
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"

          echo "SLUG=$SLUG" >> $GITHUB_ENV

      - name: Commit + Push 💪
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📝 Nouveau post: ${{ env.TITLE }}"
          branch: "article_${{ env.SLUG }}"
          create_branch: true

      - name: Créer une Pull Request 🔀
        uses: peter-evans/create-pull-request@v5
        with:
          title: "📝 Proposition d'article: ${{ env.TITLE }}"
          body: |
            Cet article a été proposé automatiquement depuis une Issue.

            Merci de le relire et de valider !
          labels: article
          base: master
          branch: "article_${{ env.SLUG }}"
