name: 🛠️ Créer un article depuis une Issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-post:
    if: contains(github.event.issue.labels.*.name, 'article')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👉🏼 Repo
        uses: actions/checkout@v4

      - name: Sauvegarder l'Issue dans un fichier temporaire
        run: echo "${{ github.event.issue.body }}" > issue.md

      - name: Extraction des données de l'Issue
        id: extract
        run: |
          TITLE=$(awk '/^\s*- type: input/{getline;getline; print}' issue.md | head -n 1 | sed 's/\r//g')
          DESCRIPTION=$(awk '/^\s*- type: textarea/{getline;getline; print}' issue.md | head -n 1 | sed 's/\r//g')
          CONTENT=$(awk '/^\s*- type: textarea/{flag=1; next} /^\s*- type: input/{flag=0} flag' issue.md | sed 's/\r//g')
          AUTHOR=$(awk '/^\s*- type: input/{getline;getline; print}' issue.md | tail -n 2 | head -n 1 | sed 's/\r//g')
          TAGS=$(awk '/^\s*- type: input/{getline;getline; print}' issue.md | tail -n 1 | sed 's/\r//g')

          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
          echo "CONTENT=$CONTENT" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Génération du fichier article
        run: |
          SLUG=$(echo "$TITLE" | iconv -f utf8 -t ascii//TRANSLIT | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-\+/-/g' | sed 's/^-//;s/-$//')
          DATE=$(date +"%d-%m-%Y")
          FILE="src/content/posts/$SLUG.md"

          mkdir -p src/content/posts

          echo "---" > "$FILE"
          echo "title: \"$TITLE\"" >> "$FILE"
          echo "description: \"$DESCRIPTION\"" >> "$FILE"
          echo "createdAt: $DATE" >> "$FILE"
          echo "author: $AUTHOR" >> "$FILE"
          echo "draft: true" >> "$FILE"
          echo "tags:" >> "$FILE"
          for tag in $(echo $TAGS | tr ',' '\n'); do
            echo "  - $(echo $tag | xargs)" >> "$FILE"
          done
          echo "---" >> "$FILE"

          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"

          echo "SLUG=$SLUG" >> $GITHUB_ENV

      - name: Commit + Push 💪
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📝 Nouveau post: $TITLE
          branch: article_$SLUG
          create_branch: true

      - name: Créer une Pull Request 🔀
        uses: peter-evans/create-pull-request@v5
        with:
          title: "📝 Proposition d'article: $TITLE
          body: "Cet article a été proposé automatiquement depuis une Issue.\n\nMerci de le relire et de valider !"
          labels: article
          base: master
          branch: article_$SLUG
