name: 🛠️ Créer un article depuis une Issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-post:
    if: contains(github.event.issue.labels.*.name, 'article')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👉🏼 master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Extraction des données
        id: extract
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.txt

          TITLE=$(awk '/^### Titre de l'\''Article/{getline; print}' issue_body.txt | xargs)
          DESCRIPTION=$(awk '/^### Description/{getline; print}' issue_body.txt | xargs)
          AUTHOR=$(awk '/^### Auteur/{getline; print}' issue_body.txt | xargs)
          TAGS=$(awk '/^### Tags/{getline; print}' issue_body.txt | xargs)
          CONTENT=$(awk '/^### Contenu complet/{flag=1; next} /^### Auteur/{flag=0} flag' issue_body.txt)

          echo "TITLE<<EOF" >> $GITHUB_ENV
          echo "$TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$DESCRIPTION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          echo "CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Générer le slug et créer la branche
        run: |
          echo "TITLE récupéré: '${{ env.TITLE }}'" # ➔ vérification visuelle
          slug=$(echo "${{ env.TITLE }}" | iconv -f utf8 -t ascii//TRANSLIT \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/[^a-z0-9]/-/g' \
            | sed 's/-\+/-/g' \
            | sed 's/^-//;s/-$//')

          echo "Slug généré: $slug"

          echo "SLUG=$slug" >> $GITHUB_ENV

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b article-$slug

      - name: Générer le fichier article
        run: |
          DATE=$(date +"%Y-%m-%d")
          FILE="src/content/posts/${{ env.SLUG }}.md"

          mkdir -p src/content/posts

          echo "---" > "$FILE"
          echo "title: \"${{ env.TITLE }}\"" >> "$FILE"
          echo "description: \"${{ env.DESCRIPTION }}\"" >> "$FILE"
          echo "createdAt: $DATE" >> "$FILE"
          echo "author: \"${{ env.AUTHOR }}\"" >> "$FILE"
          echo "draft: true" >> "$FILE"
          echo "tags:" >> "$FILE"
          for tag in $(echo "${{ env.TAGS }}" | tr ',' '\n'); do
            echo "  - $(echo $tag | xargs)" >> "$FILE"
          done
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "${{ env.CONTENT }}" >> "$FILE"

      - name: Commit + Push 💪
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📝 Proposer article: ${{ env.TITLE }}"
          create_branch: false

      - name: Créer Pull Request 🔀
        uses: peter-evans/create-pull-request@v5
        with:
          title: "📝 Proposition: ${{ env.TITLE }}"
          body: |
            Article proposé automatiquement depuis une Issue.
            Merci de le relire avant publication.
          base: master
          branch: article-${{ env.SLUG }}
